### PR TITLE
Add GitHub CI jobs

### PR DESCRIPTION
**Pull request by Mizux**
Send it, to avoid to forget it

Few notes:
* I've also removed the option `ENABLE_TESTING` so it will use the default value provided by CTest module (which is `ON`).
I would say for a CMake user, it is more common to use `-DENABLE_TESTING=OFF` than the opposite.
Feel free to remove it.

* ARM and MIPS jobs fail, I'm not 100% sure it is a runner problems nor it isn't. 
My guess, there is a real bug but since Travis-CI use cache you didn't catch it long time ago ?
todo(me): Should try to use a Dockerfile to reproduce it in a "controlled" environment... 
note: I'm not sure using cache is a really a good idea for this small project (from a CI compile time point of view ;)), small speedup at the cost of missing some bugs ?

* With GitHUb actions you can have a badge per yaml file, so if you split it you can have a badge for ARM, MIPS, Native etc...
e.g. with link to the workflow (don't hesitate to "edit" my post to see the markdown code)

[![Status][arm_svg]][arm_link]
[![Status][native_svg]][native_link]

[arm_svg]: https://github.com/google/cpu_features/workflows/ARM/badge.svg?branch=master
[arm_link]: https://github.com/google/cpu_features/actions?query=workflow%3A"ARM"
[native_svg]: https://github.com/google/cpu_features/workflows/Native/badge.svg?branch=master
[native_link]: https://github.com/google/cpu_features/actions?query=workflow%3A"Native"

```
[![Status][arm_svg]][arm_link]

[arm_svg]: https://github.com/google/cpu_features/workflows/ARM/badge.svg?branch=master
[arm_link]: https://github.com/google/cpu_features/actions?query=workflow%3A"ARM"
```

### CODE REVIEW

**Comment by Mizux** [comment]
Comparing Travis-CI and GitHUb actions trace, travis-ci has already install qemu so worker didn't try to rebuild it while on github action it failed while building it

ref: for aarch64
* https://pipelines.actions.githubusercontent.com/4PhP80PVRjrauHWV4V3uBqw0G4ZPm73uB9cHYNNdgtJUVMnFvh/_apis/pipelines/1/runs/51/signedlogcontent/4?urlExpires=2020-10-27T12%3A17%3A07.8850850Z&urlSigningMethod=HMACV1&urlSignature=TYNT9UYO8VkHkqHJTxKxCcjOnNn5Lnxx%2Bwg18gjic28%3D
* https://api.travis-ci.org/v3/job/739264181/log.txt

travis trace
```
...
+[[ -n aarch64 ]]
+installqemuifneeded
+local VERSION=2.11.1
+local ARCHES=aarch64
++echo aarch64
++sed 's#$# #;s#\([^ ]*\) #\1-linux-user #g'
+local 'TARGETS=aarch64-linux-user '
+echo '2.11.1 aarch64-linux-user '
+cmp --silent /home/travis/cpu_features_archives/qemu/.build -
+echo 'qemu 2.11.1 up to date!'
qemu 2.11.1 up to date!
```

githubtrace
```
...
2020-10-27T11:50:19.3438647Z + [[ -n aarch64 ]]
2020-10-27T11:50:19.3439307Z + installqemuifneeded
2020-10-27T11:50:19.3439995Z + local VERSION=2.11.1
2020-10-27T11:50:19.3440542Z + local ARCHES=aarch64
2020-10-27T11:50:19.3441084Z ++ echo aarch64
2020-10-27T11:50:19.3441954Z ++ sed 's#$# #;s#\([^ ]*\) #\1-linux-user #g'
2020-10-27T11:50:19.3442993Z + local 'TARGETS=aarch64-linux-user '
2020-10-27T11:50:19.3444694Z + cmp --silent /home/runner/cpu_features_archives/qemu/.build -
2020-10-27T11:50:19.3445919Z + echo '2.11.1 aarch64-linux-user '
2020-10-27T11:50:19.3446827Z + echo 'VERSION: 2.11.1'
2020-10-27T11:50:19.3447798Z + echo 'TARGETS: aarch64-linux-user '
2020-10-27T11:50:19.3448939Z + rm -rf /home/runner/cpu_features_archives/qemu
2020-10-27T11:50:19.3450604Z + local QEMU_URL=http://wiki.qemu-project.org/download/qemu-2.11.1.tar.xz
2020-10-27T11:50:19.3452109Z + local QEMU_FOLDER=qemu-2.11.1
2020-10-27T11:50:19.3453871Z + unpackifnotexists http://wiki.qemu-project.org/download/qemu-2.11.1.tar.xz qemu-2.11.1
2020-10-27T11:50:19.3455623Z + mkdir -p /home/runner/cpu_features_archives
.... // few dozen of lines
2020-10-27T11:51:00.1323858Z   CC      util/memfd.o
2020-10-27T11:51:00.3591803Z util/memfd.c:40:12: error: static declaration of ‘memfd_create’ follows non-static declaration
2020-10-27T11:51:00.3593049Z  static int memfd_create(const char *name, unsigned int flags)
2020-10-27T11:51:00.3594150Z             ^~~~~~~~~~~~
2020-10-27T11:51:00.3636699Z In file included from /usr/include/x86_64-linux-gnu/bits/mman-linux.h:115:0,
2020-10-27T11:51:00.3638002Z                  from /usr/include/x86_64-linux-gnu/bits/mman.h:45,
2020-10-27T11:51:00.3638932Z                  from /usr/include/x86_64-linux-gnu/sys/mman.h:41,
2020-10-27T11:51:00.3639998Z                  from /home/runner/cpu_features_archives/qemu-2.11.1/include/sysemu/os-posix.h:29,
2020-10-27T11:51:00.3641197Z                  from /home/runner/cpu_features_archives/qemu-2.11.1/include/qemu/osdep.h:104,
2020-10-27T11:51:00.3641922Z                  from util/memfd.c:28:
2020-10-27T11:51:00.3643357Z /usr/include/x86_64-linux-gnu/bits/mman-shared.h:46:5: note: previous declaration of ‘memfd_create’ was here
2020-10-27T11:51:00.3644164Z  int memfd_create (const char *__name, unsigned int __flags) __THROW;
2020-10-27T11:51:00.3644580Z      ^~~~~~~~~~~~
2020-10-27T11:51:00.3727183Z make: *** [util/memfd.o] Error 1
2020-10-27T11:51:00.3728405Z /home/runner/cpu_features_archives/qemu-2.11.1/rules.mak:66: recipe for target 'util/memfd.o' failed
2020-10-27T11:51:00.3729130Z make: *** Waiting for unfinished jobs....
2020-10-27T11:51:00.9876714Z ##[error]Process completed with exit code 2.
2020-10-27T11:51:00.9959391Z Post job cleanup.
2020-10-27T11:51:01.1096020Z [command]/usr/bin/git version
2020-10-27T11:51:01.1163505Z git version 2.28.0
2020-10-27T11:51:01.1201327Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-10-27T11:51:01.1246405Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-10-27T11:51:01.1551615Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-10-27T11:51:01.1592216Z http.https://github.com/.extraheader
2020-10-27T11:51:01.1602393Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-10-27T11:51:01.1648172Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-10-27T11:51:01.2010194Z Cleaning up orphan processes
```

**Comment by Mizux** [comment]
runners specification: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

**Review by gchatelet — CHANGES_REQUESTED** [review]
As discussed, let's focus on adding the FreeBSD CI via Vagrant first and I'll take care of enabling `cpu_features` for FreeBSD in a second patch. Thx!

**Comment by Mizux** [comment]
This branch now contains patchs for:
* FreeBSD test through use of Vagrant
* Github Workflow CI
* FreeBSD quick patch to make it run

-> let's close this corrupted PR and i'll try to recreate a separate ones for each tasks (except the one you take the lead on ;))

**Pull request closed without merging**
