### PR TITLE
Avoid if-clause in CpuFeatures_StringView_IsEquals()

### PR DESCRIPTION
**Pull request by psiegl**

### CODE REVIEW

**Comment by psiegl** [comment]
Less if/else-clauses mean less testing effort required. Well yes, it is debatable if moving if-clause into longer boolean expression is better. From my perspective: yes ;-)

**Comment by gchatelet** [comment]
> Less if/else-clauses mean less testing effort required.
How come?

**Comment by psiegl** [comment]
> How come?
I get your point: the code does just a conversion from an if/else-clause to a boolean expression and is therefore equal. Feel free to merge or close it.

**Comment by gchatelet** [comment]
Let's keep it as is then. Thx!

**Pull request closed without merging**
