### PR TITLE
Update AArch64 features to Linux 5.17.

### PR DESCRIPTION
**Pull request by tamaszarm**
Adds three new features: ecv, afp and rpres.

### CODE REVIEW

**Comment by toor1245** [comment]
for the record, in [5.18-rc1](https://elixir.bootlin.com/linux/v5.18-rc1/source/arch/arm64/kernel/cpuinfo.c) added `mte3`

**Review by toor1245 — APPROVED** [review]

**Comment by toor1245** [comment]
@gchatelet, @Mizux please review PR, approved from my side

**Review by Mizux — APPROVED** [review]
Confirmed by 
https://elixir.bootlin.com/linux/v5.17.4/source/arch/arm64/kernel/cpuinfo.c#L97

**Comment by gchatelet** [comment]
Thx for the PR @tamaszarm and thx for the review @Mizux and @toor1245 .

**Pull request merged**
