### PR TITLE
Explicitly namespace every extern identifier

### PR DESCRIPTION
**Pull request by Leandros**
To avoid identifier collisions and fix https://github.com/google/cpu_features/issues/34, I moved every extern identifier into their own "namespace", by prefixing them with `CpuFeatures_` (or `CpuFeatures_ClassName_`, for example for the `StringView`: `CpuFeatures_StringView_`).

I'm aware this is a huge change, but it's, unfortunately, required since C has no explicit namespaces. The other option would be to migrate to C++ and use actual namespaces.
I only did a search & replace for the identifiers, the change is likely to violate some 80 column limits and would need to be reformatted at some points. 

Tested and compiles on macOS. 

**Edit:** I also just realized I haven't updated the tests.

### CODE REVIEW

**Comment by Leandros** [comment]
Signed.

**Comment by gchatelet** [comment]
Thx a lot for the PR @Leandros .
Do you mind updating the tests and running `git clang-format` ?

**Comment by gchatelet** [comment]
Also, can we fix only the filesystem API for now and not touch capabilities and stringview?

I believe that `struct StringView` has more chance to collide with existing code than the functions working on it.

**Comment by Leandros** [comment]
> I believe that struct StringView has more chance to collide with existing code than the functions working on it.

That doesn't matter, since that collision would only occur if you'd actually include the `string_view.h` header into your own code. The StringView functions, on the other hand, are in the global namespace, and will be accessible by any program or library which is also linked into the same application as this library. And I'd say, a function like `Push` or `Back` can very likely appear in some C or C++ programs.

**Comment by tbodt** [comment]
If the StringView functions are only called by the library, and wouldn't be called by any users of the library, they could be marked as `__attribute__((visibility("hidden")))` or the equivalent on windows (not sure what that is).

**Comment by Leandros** [comment]
That's a good idea, which would reduce the amount of change required.

**Comment by gchatelet** [comment]
> That doesn't matter, since that collision would only occur if you'd actually include the string_view.h header into your own code. The StringView functions, on the other hand, are in the global namespace, and will be accessible by any program or library which is also linked into the same application as this library. And I'd say, a function like Push or Back can very likely appear in some C or C++ programs.

@Leandros you're right. I forgot `C` does not mangle function names and that's indeed [ODR violation](https://en.wikipedia.org/wiki/One_Definition_Rule).

I think the visibility way is promising (and adds less clutter to the code). IIRC MSVC does not export symbols if not marked `__declspec(dllexport)` so it should already work properly with MSVC. Can you confirm you used GCC or Clang?

Meanwhile, I'll work on a fix based on @tbodt suggestion (thx @tbodt!)

**Comment by Leandros** [comment]
I used MSVC. `__declspec(dllexport)` only works for DLLs, not for static libraries.

**Comment by Leandros** [comment]
Tests should be fixed now. You'd have to run `clang-format`, though. Seems my clang-format 5.0.1 is to old to recognize the config file.

**Comment by gchatelet** [comment]
As for clang-format, it may be because of a missing line feed at the end of the file.
I submitted a fix. Can you patch the PR and try again?

**Comment by Leandros** [comment]
Lovely, that seems to work. I've fixed the failing tests and re-formated all files.

**Comment by gchatelet** [comment]
Fantastic! Thank you for your contribution, your time and for bearing with me :) My `C` is quite rusted as you can see :)

**Pull request merged**
