### PR TITLE
ci: Add bazel jobs

### PR DESCRIPTION
**Pull request by Mizux**
* [optional] Use `git_repository()` to retrieve dependencies
* Add amd64 Linux Bazel based build jobs.

### CODE REVIEW

**Comment by Mizux** [comment]
MacOS and Windows are currently broken. I think it's an issue in our BUILD files not in jobs...

**Comment by gchatelet** [comment]
As discussed offline let's:
 - remove the `build` part and keep only `test`
 - remove the `-c opt`
 - split the PR in three, one for Linux that we can submit right away and two branches for Mac and Windows so we can fix them

**Comment by Mizux** [comment]
@gchatelet PTAL

note: I've just added the branch `bazel/windows` and `bazel/macos` feel free to commit in it to test/fix/iterate etc...

**Comment by gchatelet** [comment]
LGTM Thx!

**Pull request merged**
